
POST http://localhost:3000/schemes/loadLibrary
Content-Type: application/json

{
    "login": "testowy1",
    "pass": "111"
}

###

POST http://localhost:3000/schemes/saveLibrary
Content-Type: application/json

{
    "login": "testowy1",
    "pass": "111",
    "schemes":[
        {
            "name": "test",
            "id": "D7E46E35-4FC1-4D62-82AB-A405959EB76A",
            "colors":[
                {
                    "name": "",
                    "color":"FFFFF0"
                },
                {
                    "name": "black",
                    "color":"000000"
                }
            ],
            "lastUpdate":"2021-03-21T11:50:45.463Z"
        },
        {
            "name": "aaaa",
            "id": "D7E46E35-4FC1-4D62-82AB-A405959EB700",
            "colors":[
                {
                    "name": "black",
                    "color":"000000"
                }
            ],
            "lastUpdate":"2021-03-21T11:50:45.463Z"
        }
    ]
}

###

POST http://localhost:3000/schemes/saveLibrary
Content-Type: application/json

{
    "login": "testowy1",
    "pass": "111",
    "schemes":[
        {
            "name": "testowy 1",
            "id": "D7E46E35-4FC1-4D62-82AB-A405959EB76A",
            "colors":[
                {
                    "name": "white",
                    "color":"FFFFF0"
                }
            ],
            "lastUpdate":"2021-03-21T11:50:45.463Z"
        }
    ]
}

###

POST http://localhost:3000/schemes/saveLibrary
Content-Type: application/json

{
    "login": "testowy1",
    "pass": "111",
    "schemes":[
    ]
}
