
GET  http://localhost:3000/settings
x-user: testowy1
x-access: txlHm5R1yNb26+CwcNuoazZevUrxTLfQBbc+1SRsakM=

###

GET http://localhost:3000/settings
x-user: testowy2
x-access: 123

###

POST http://localhost:3000/settings
x-user: testowy1
x-access: txlHm5R1yNb26+CwcNuoazZevUrxTLfQBbc+1SRsakM=
Content-Type: application/json

{
    "lightBackgroundColor":"#ffffff",
    "lightTextColor":"#ffffff",
    "darkTextColor":"#333333",
    "darkBackgroundColor":"#333333",
    "lastUpdate": "2021-03-21T11:50:45.463Z",
    "autoSync": false
}

###

POST http://localhost:3000/settings
x-user: testowy2
x-access: 123
Content-Type: application/json

{
    "login": "testowy2",
    "pass": "123",
    "lightBackgroundColor":"#ffffff",
    "lightTextColor":"#ffffff",
    "darkTextColor":"#666666",
    "darkBackgroundColor":"#333333"
    
}