
GET  http://localhost:3000/users/validate
x-user: testowy1
x-access: txlHm5R1yNb26+CwcNuoazZevUrxTLfQBbc+1SRsakM=

###

GET http://localhost:3000/users/validate
x-user: testowy2
x-access: 222

###

POST http://localhost:3000/users/new
Content-Type: application/json

{
    "token": "test-token-01",
    "login": "testowy1",
    "pass": "111"
}

###

POST http://localhost:3000/users/new
Content-Type: application/json

{
    "token": "test-token-01",
    "login": "testowy2",
    "pass": "123"
}